# Generated by Django 5.1.6 on 2025-02-14 15:12

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_companyfounder_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=128)),
                ('collaboration_type', models.CharField(choices=[('0', 'full_time'), ('1', 'part_time'), ('2', 'remote'), ('3', 'hybrid')], max_length=128)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=128)),
                ('immediate', models.BooleanField(default=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education', models.CharField(choices=[('0', 'diploma'), ('1', 'associate_degree'), ('2', 'bachelors'), ('3', 'masters'), ('4', 'phd')], max_length=32)),
                ('duty_system', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'finished'), ('1', 'exempt'), ('2', 'inductee'), ('3', 'academic_exemption')], max_length=50), blank=True, null=True, size=None)),
                ('gender', models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Unknown')], max_length=1)),
                ('salary_type', models.CharField(choices=[('0', 'fixed salary'), ('1', 'salary range'), ('2', 'negotiable')], default='2', max_length=32)),
                ('salary_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_range', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.companyfounder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('0', 'pending'), ('1', 'seen'), ('2', 'interview'), ('3', 'hired'), ('4', 'rejected')], default='0', max_length=32)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to='accounts.jobseeker')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job', to='jobs.job')),
            ],
            options={
                'unique_together': {('job_seeker', 'job')},
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_job', to='jobs.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='accounts.jobseeker')),
            ],
            options={
                'unique_together': {('job', 'job_seeker')},
            },
        ),
    ]
