# Generated by Django 5.1.6 on 2025-02-12 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='accounts.companyfounder')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
