# Generated by Django 5.1.6 on 2025-02-14 15:12

import common.validations
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companystaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfounder',
            name='company_logo',
            field=models.ImageField(upload_to=common.validations.generate_filename, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), common.validations.validate_file_size]),
        ),
    ]
